[project]
name = "coherent_rates"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.14"
authors = [{ name = "Matthew Ord", email = "matthew.ord1@gmail.com" }]
dependencies = ["surface-potential-analysis"]

[dependency-groups]
dev = ["pyright[nodejs]>=1.1.408,<2.0.0", "ruff", "pytest>=8.0.1,<9.0.0"]


[tool.setuptools.packages.find]
where = ["."]
include = ["coherent_rates*"]

[tool.ruff]
unsafe-fixes = true
extend-exclude = ["lib/**/*"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D100",
    "D417",
    "TD003",
    "TD002",
    "D203",
    "D213",
]
unfixable = ["ERA001", "T201"]

[tool.ruff.lint.extend-per-file-ignores]
"examples/**/*" = ["T201", "INP001", "INP001"]
"scripts/**/*" = ["INP001"]
"tests/**/*" = ["INP001"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
ignore = ["lib"]

[tool.uv.sources]
"surface-potential-analysis" = { path = "lib/surface_potential_analysis", editable = true }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
